#!/bin/bash

echo -e "===\n>> Pre-commit Hook: Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|develop|main)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot commit to $BRANCH branch, please create your own branch and use PR." && exit 1
fi

echo -e ">> Finish checking branch name.\n==="

echo -e "===>> Pre-commit Hook: Run linters and formatters"
yarn run lint-staged
echo -e "===>> Pre-commit Hook: Finish linters and formatters"